- name: Check if SSH private key exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  register: ssh_key

- name: Generate SSH key pair
  ansible.builtin.command:
    cmd: ssh-keygen -t rsa -N "" -f "{{ ansible_env.HOME }}/.ssh/id_rsa"
  when: not ssh_key.stat.exists

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Add public key to authorized_keys
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    line: "{{ lookup('file', ansible_env.HOME + '/.ssh/id_rsa.pub') }}"
    state: present
    mode: "0600"
