- name: Set ulimit for file descriptors in limits.conf
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: "*   hard   nofile   10000"
    state: present

- name: Configure pam_limits.so for sessions
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    line: "session required pam_limits.so"
    state: present

- name: Configure pam_limits.so for non-interactive sessions
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session-noninteractive
    line: "session required pam_limits.so"
    state: present
